<?php

use Illuminate\Database\Seeder;

class MateriasSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /*AGREGAR MATERIAS */
        
DB::table('materias')->insert(['nombre'=>'INGLÉS I','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'VALORES DEL SER','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'ALGORITMOS','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'HERRAMIENTAS OFIMÁTICAS','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'ARQUITECTURA DE COMPUTADORAS','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'LÓGICA COMPUTACIONAL','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INTRODUCCIÓN A LA ITI','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'TALLER DE ALGEBRA','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'TALLER DE TECNOLOGÍAS DE LA INFORMACIÓN','id_carrera'=>2,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INGLÉS II','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INTELIGENCIA EMOCIONAL','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN ESTRUCTURADA','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'HERRAMIENTAS MULTIMEDIA','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE REDES','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'MATEMÁTICAS DISCRETAS','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'MATEMÁTICAS BASICAS','id_carrera'=>2,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INGLÉS III','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'DESARROLLO INTERPERSONAL','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'INTROD. A LA PROG. ORIENTADA A OBJETOS','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ADMINISTRACIÓN DE SISTEMAS OPERATIVOS','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'RUTEO','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'INTRODUCCIÓN A LAS BASES DE DATOS','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO DIFERENCIAL E INTEGRAL','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE SISTEMAS DE INFORMACIÓN','id_carrera'=>2,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'TALLER DE REDES','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IV','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES DEL PENSAMIENTO','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'ESTRUCTURAS DE DATOS','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA DE REQUERIMIENTOS','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'SWITCHEO Y WIRELESS','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'DISEÑO DE BASES DE DATOS','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'PROBABILIDAD Y ESTADÍSTICA','id_carrera'=>2,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'TALLER DE PROGRAMACIÓN CON BASES DE DATOS','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGLÉS V','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES ORGANIZACIONALES','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN ORIENTADA A OBJETOS','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA DE SOFTWARE','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'TECNOLOGÍAS WAN','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'IMPLEMENTACIÓN DE BASES DE DATOS','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE FÍSICA','id_carrera'=>2,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VI','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ÉTICA PROFESIONAL','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ANALISIS Y DISEÑO ORIENTADO A OBJETOS','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ANÁLISIS Y DISEÑO DE SISTEMAS','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'SEGURIDAD INFORMÁTICA','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA I','id_carrera'=>2,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VII','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'DESARROLLO DE EMPRENDEDORES','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN WEB','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'PROYECTOS DE TECNOLOGIAS DE LA INFORMACIÓN','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'ARQUITECTURA DE APLICACIONES EMPRESARIALES','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'NEGOCIOS ELECTRÓNICOS','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'ÁLGEBRA LINEAL','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'MINERÍA DE DATOS APLICADA','id_carrera'=>2,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VIII','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ADMINISTRACIÓN DE SISTEMAS INTEGRALES','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'DISEÑO DE INTERFACES','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'PROCESO ADMINISTRATIVO','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ARQUITECTURA DE SOLUCIONES MÓVILES EMPRESARIALES','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA II','id_carrera'=>2,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IX','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INTEGRACIÓN DE TECNOLOGÍAS DE LA INFORMACIÓN','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'TECNOLOGÍA Y APLICACIONES WEB','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO INVESTIGACIÓN','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN MVC','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INTELIGENCIA DE NEGOCIOS','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ADMINISTRACIÓN DE CENTROS DE COMPUTO','id_carrera'=>2,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ESTADÍA','id_carrera'=>2,'cuatrimestre'=>'10']);
DB::table('materias')->insert(['nombre'=>'ÁLGEBRA LINEAL','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INGLÉS I','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INTRODUCCIÓN A LA INGENIERÍA EN ENERGÍA','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'MECÁNICA CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'TRANSFORMACIONES QUÍMICAS CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'VALORES DEL SER','id_carrera'=>3,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO DIFERENCIAL','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'ELECTRICIDAD Y MAGNETISMO CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INGLÉS II','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INTELIGENCIA EMOCIONAL','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'LABORATORIO DE SIMULACIÓN Y DISEÑO POR COMPUTADORA','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'MECÁNICA DE FLUIDOS CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE INGENIERÍA EN ENERGÍA TÉRMICA','id_carrera'=>3,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO INTEGRAL','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'DESARROLLO INTERPERSONAL','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ELECTROQUÍMICA','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'INGLÉS III','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'MÁQUINAS ELÉCTRICAS','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE INGENIERIA EN ENERGÍA EÓLICA','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'TRANSFERENCIA DE CALOR Y MASA','id_carrera'=>3,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO DE VARIAS VARIABLES','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'ENERGÍA DEL HIDRÓGENO CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'FÍSICA MODERNA','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES DEL PENSAMIENTO','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IV','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'ÓPTICA','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE INGENIERÍA EN ENERGÍA DEL HIDRÓGENO','id_carrera'=>3,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'CELDAS DE COMBUSTIBLE','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'ECUACIONES DIFERENCIALES','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'ESTADO SÓLIDO','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES ORGANIZACIONALES','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGLÉS V','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE INGENIERIA EN ENERGÍA FOTOVOLTAICA','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS FOTOVOLTAICOS CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'BIOMASA CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ECUACIONES DIFERENCIALES PARCIALES','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA I','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ÉTICA PROFESIONAL','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VI','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE INGENIERÍA EN ENERGÍA DE BIOMASA','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'TERMODINÁMICA CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'CONTABILIDAD EMPRESARIAL','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'FÍSICA NUCLEAR CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA AMBIENTAL','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VII','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'METROLOGÍA E INSTRUMENTACIÓN','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'SEGURIDAD INDUSTRIAL','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS TÉRMICOS','id_carrera'=>3,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'AHORRO Y USO EFICIENTE DE ENERGÍA','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ALMACENAMIENTO DE ENERGÍA SOLAR','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ENERGÍA HIDRÁULICA CON LABORATORIO','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA II','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA ENERGÉTICA','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VIII','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'MÁQUINAS TÉRMICAS','id_carrera'=>3,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'CICLOS COMBINADOS','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ÉTICA EN LOS NEGOCIOS','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'GESTIÓN DE PROYECTOS','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IX','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INNOVACIÓN TECNOLÓGICA','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INTRODUCCION A LA ADMINISTRACION','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'INTRODUCCIÓN A LA ARQUITECTURA BIOCLIMÁTICA','id_carrera'=>3,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ESTADÍA','id_carrera'=>3,'cuatrimestre'=>'10']);
DB::table('materias')->insert(['nombre'=>'INGLÉS I','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'VALORES DEL SER','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'TOPICOS DE INGENIERIA EN ELECTRONICA Y TELECOMUNICACIONES','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'ÁLGEBRA LINEAL','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO DIFERENCIAL E INTEGRAL','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'LÓGICA DE PROGRAMACIÓN','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'PROBABILIDAD Y ESTADÍSTICA','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INGLÉS II','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INTELIGENCIA EMOCIONAL','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'MANTENIMIENTO ELECTRÓNICO','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE FÍSICA','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO VECTORIAL','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN ESTRUCTURADA (IET)','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE QUÍMICA','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INGLÉS III','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'DESARROLLO INTERPERSONAL','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS EN CORRIENTE DIRECTA','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS LÓGICOS','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ECUACIONES DIFERENCIALES','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN DE PERIFÉRICOS','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ELECTRICIDAD Y MAGNETISMO','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IV','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES DEL PENSAMIENTO','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS EN CORRIENTE ALTERNA','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DIGITALES','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'MÉTODOS MATEMÁTICOS','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'ANÁLISIS DE DISPOSITIVOS ELECTRÓNICOS','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'TEORÍA ELECTROMAGNÉTICA','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'INGLÉS V','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES ORGANIZACIONALES','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA DE CONTROL','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'DISEÑO DIGITAL','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'MÉTODOS NUMÉRICOS','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE AMPLIFICACIÓN','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'PROCESOS ESTOCÁSTICOS','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VI','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ÉTICA PROFESIONAL','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'MICROCONTROLADORES','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'REDES DE COMUNICACIONES','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'MODULACIONES ANALÓGICAS','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'FILTROS ANALÓGICOS','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA I','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VII','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INSTRUMENTACIÓN ELECTRÓNICA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'GESTIÓN ADMINISTRATIVA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'CONTROL INDUSTRIAL','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'MODULACIONES DIGITALES','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'PLC-S','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE TELEFONÍA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VIII','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ANTENAS Y LÍNEAS DE TRANSMISIÓN','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'CONTROL DE CALIDAD','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'CONTROL DIGITAL','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'PROCESAMIENTO DIGITAL DE SEÑALES','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'COMUNICACIONES DIGITALES','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA II','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IX','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ELECTRÓNICA DE POTENCIA','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'REDES DE COMUNICACIONES INDUSTRIALES','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ENERGÍAS ALTERNAS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'CONTROL DE PROCESOS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE COMUNICACIONES INALÁMBRICAS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE PROYECTOS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ESTADÍA','id_carrera'=>4,'cuatrimestre'=>'10']);
DB::table('materias')->insert(['nombre'=>'VALORES DEL SER','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'TOPICOS DE INGENIERIA EN ELECTRONICA Y TELECOMUNICACIONES','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'ÁLGEBRA LINEAL','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO DIFERENCIAL E INTEGRAL','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'LÓGICA DE PROGRAMACIÓN','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'PROBABILIDAD Y ESTADÍSTICA','id_carrera'=>4,'cuatrimestre'=>'1']);
DB::table('materias')->insert(['nombre'=>'INGLÉS II','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INTELIGENCIA EMOCIONAL','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'MANTENIMIENTO ELECTRÓNICO','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE FÍSICA','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'CÁLCULO VECTORIAL','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN ESTRUCTURADA (IET)','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'FUNDAMENTOS DE QUÍMICA','id_carrera'=>4,'cuatrimestre'=>'2']);
DB::table('materias')->insert(['nombre'=>'INGLÉS III','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'DESARROLLO INTERPERSONAL','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS EN CORRIENTE DIRECTA','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS LÓGICOS','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ECUACIONES DIFERENCIALES','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'PROGRAMACIÓN DE PERIFÉRICOS','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'ELECTRICIDAD Y MAGNETISMO','id_carrera'=>4,'cuatrimestre'=>'3']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IV','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES DEL PENSAMIENTO','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'CIRCUITOS EN CORRIENTE ALTERNA','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DIGITALES','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'MÉTODOS MATEMÁTICOS','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'ANÁLISIS DE DISPOSITIVOS ELECTRÓNICOS','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'TEORÍA ELECTROMAGNÉTICA','id_carrera'=>4,'cuatrimestre'=>'4']);
DB::table('materias')->insert(['nombre'=>'INGLÉS V','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'HABILIDADES ORGANIZACIONALES','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGENIERÍA DE CONTROL','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'DISEÑO DIGITAL','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'MÉTODOS NUMÉRICOS','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE AMPLIFICACIÓN','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'PROCESOS ESTOCÁSTICOS','id_carrera'=>4,'cuatrimestre'=>'5']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VI','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ÉTICA PROFESIONAL','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'MICROCONTROLADORES','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'REDES DE COMUNICACIONES','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'MODULACIONES ANALÓGICAS','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'FILTROS ANALÓGICOS','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA I','id_carrera'=>4,'cuatrimestre'=>'6']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VII','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INSTRUMENTACIÓN ELECTRÓNICA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'GESTIÓN ADMINISTRATIVA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'CONTROL INDUSTRIAL','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'MODULACIONES DIGITALES','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'PLC-S','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE TELEFONÍA','id_carrera'=>4,'cuatrimestre'=>'7']);
DB::table('materias')->insert(['nombre'=>'INGLÉS VIII','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ANTENAS Y LÍNEAS DE TRANSMISIÓN','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'CONTROL DE CALIDAD','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'CONTROL DIGITAL','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'PROCESAMIENTO DIGITAL DE SEÑALES','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'COMUNICACIONES DIGITALES','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'ESTANCIA II','id_carrera'=>4,'cuatrimestre'=>'8']);
DB::table('materias')->insert(['nombre'=>'INGLÉS IX','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ELECTRÓNICA DE POTENCIA','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'REDES DE COMUNICACIONES INDUSTRIALES','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ENERGÍAS ALTERNAS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'CONTROL DE PROCESOS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'SISTEMAS DE COMUNICACIONES INALÁMBRICAS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'SEMINARIO DE PROYECTOS','id_carrera'=>4,'cuatrimestre'=>'9']);
DB::table('materias')->insert(['nombre'=>'ESTADÍA','id_carrera'=>4,'cuatrimestre'=>'10']);

        
    }
}
